version: '3.4'

networks:
  webdocker-dev:
    driver: bridge

services:
  webdocker:
        image: webdocker
        depends_on: 
            - "postgresql_image"
        build:
             context: .
             dockerfile: Dockerfile
        ports: 
         - "8000:80"
        environment: 
            DB_CONNECTION_STRING: "host=postgresql_image;port=5432;database=gadget;username=postgres;password=admin"
        networks: 
         - webdocker-dev
  postgresql_image:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gadget
    ports: 
      - "5432:5432"
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    networks: 
       - webdocker-dev